---
abstract: 'Add colors to DNA and RNA sequences in terminal output'
author:
  - 'Ryan C. Thompson <rct@thompsonclan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Term::ANSIColor: 2.01
  Test::More: 0.94
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-DNAColor
requires:
  Exporter::Simple: 0
  Term::ANSIColor: 0
  perl: 5.008
  utf8: 0
resources:
  homepage: http://github.com/DarwinAwardWinner/Term-DNAColor/tree
  repository: git://github.com/DarwinAwardWinner/Term-DNAColor.git
version: 0.110230
